FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y file wget libgtk-3-dev

# Download appimagetool
RUN wget "https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20220822-1/linuxdeploy-x86_64.AppImage" -O /usr/local/bin/linuxdeploy

# Edit appimagetool permissions
RUN chmod a+x /usr/local/bin/linuxdeploy

WORKDIR /
COPY ./keechain.AppDir /keechain.AppDir
COPY entrypoint.sh .
RUN chmod a+x /entrypoint.sh
RUN mkdir -p /output

ENTRYPOINT ["/entrypoint.sh"]
